### ISSUE TITLE
Percorso Fisso del File

### ISSUE THREAD

**Issue by guarrasi1995** [virginiasimoncini/Progetto_Programmazione#10]
Il percorso del file CSV è hard-coded, il che limita la flessibilità e la portabilità del codice. Considera di rendere il percorso del file un parametro della funzione o di utilizzare un approccio più flessibile per la specifica del percorso del file, come un percorso relativo o la lettura da una variabile di ambiente o un file di configurazione.

**Comment by KosmicKatXV** [comment]
Questo issue e incluso sulla nuova versione e sarà chiuso.

**Comment by KosmicKatXV** [comment]
Questo issue e incluso sulla nuova versione e sarà chiuso.
