### ISSUE TITLE
Input utente

### ISSUE THREAD

**Issue by guarrasi1995** [virginiasimoncini/Progetto_Programmazione#12]
non avete svolto la richiesta di richiesta all'utente su:
quali metriche devono essere validate:
o AccuracyRate
o ErrorRate
o Sensitivity
o Specificity
o GeometricMean
o All the above

**Comment by GraziaDebora** [comment]
Prof abbiamo messo un menu sul main per far scegliere all'utente che metriche considerare nel caso di Holdout,nel caso di CV abbiamo lasciato come c'era la acc mean.

**Comment by guarrasi1995** [comment]
La scelta delle metriche deve valere sia per Holdout che per CV.
Vi ricordo che calcolare le metriche in CV è uguale calcolarne in Holdout, ma n volte (n = # di esperimenti), su cui poi si calcola una media finale. Dunque, organizzate il vostro codice in modo tale che sfruttate la stessa funzione più volte senza doverla riscrivere.

**Comment by GraziaDebora** [comment]
Prof abbiamo appena provveduto a pushare la nuova versione del codice con le fix.
