### ISSUE TITLE
Holdout vs CV

### ISSUE THREAD

**Issue by guarrasi1995** [virginiasimoncini/Progetto_Programmazione#13]
Istanziazione di oggetti (come Holdout e XXCrossValidation in questo caso) per poi potenzialmente non utilizzarli tutti a seconda della scelta dell'utente può sembrare inefficiente in termini di utilizzo delle risorse, soprattutto se l'inizializzazione di tali oggetti è costosa in termini di tempo o di memoria.

Un approccio più efficiente potrebbe essere ritardare l'istanziazione degli oggetti fino a quando non è chiaro quale di essi sarà effettivamente utilizzato. Magari in una funzione che gestisce la scelta.

**Comment by GraziaDebora** [comment]
Prof ho appena committato la fix, ho permesso l'input dell'utente tramite una scelta, aggiunto una gestione della scelta in modo tale che finchè l'utente non mi mette la scelta giusta cadrà in eccezione,. Una volta che l'utente mi sceglie il tipo di analisi che preferisce allora chiederò k per i vicini holdout o num folds per cv (possiamo anche chiamarlo diversamente tipo "mini data-set" ma questo possiamo gestirlo facilmente).
